config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
	get 'user/articles' ,to: 'articles#myarticles'
  devise_for :users, :controllers=>{registrations:"users/registrations"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :articles do
  	resources :comments
  end

  root 'articles#index'
  
end

app/views/layouts/_navigationbar.html.erb
<nav class="navbar navbar-expand-sm fixed-top navbar-dark bg-dark">
  <%= link_to 'Blog Application', articles_path, :class => 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample03" aria-controls="navbarsExample03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExample03">
    <ul class="navbar-nav mr-auto">

      
      <li class="nav-item">
        <%= link_to 'Home', articles_path, :class => 'nav-link' %>
      </li>
      
      <% if user_signed_in?%>
        
        <li class="nav-item">
          <%= link_to 'My Articles', user_articles_path, :class => 'nav-link' %>
        </li>

        <li class="nav-item">
          <%= link_to 'New article', new_article_path , :class => 'nav-link'%>
        </li>

      <%end%>

      <li class="nav-item">
        <a class="nav-link" href="#">Search Articles</a>
      </li>
      
    </ul>
    <form class="form-inline my-2 my-md-0">
      <span class="navbar-text">
          <% if user_signed_in? %>

            Logged in as <strong><%= current_user.name %></strong>

            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-btn btn btn-dark' %>
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-btn btn btn-dark'  %> 

          <% else %>
            <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-btn btn btn-dark'  %> 
            <%= link_to "Login", new_user_session_path, :class => 'navbar-btn btn btn-dark'  %> 
          <% end %>
          <%= link_to "My Blog", articles_path , :class => 'navbar-btn btn btn-dark'  %>
        </span>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= javascript_include_tag Ckeditor.cdn_url%>
    <title>BlogApplication</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    
  </head>

  <body>

    <%= render partial: "layouts/navigationbar"%>

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>

  </body>
</html>